FROM amazoncorretto:22-jdk AS builder

FROM amazoncorretto:22-jdk

WORKDIR /app

COPY pbelcar_vjezba_08_dz_3_app/target/pbelcar_vjezba_08_dz_3_app-1.1.0-jar-with-dependencies.jar /app/jar_file.jar
COPY pbelcar_vjezba_08_dz_3_app/NWTiS_DZ1_R2.txt NWTiS_DZ1_R2.txt
COPY docker-entrypoint.radar2.sh /app/script.sh

RUN chmod 777 /app/script.sh

ENTRYPOINT ["/app/script.sh"]
